services:
  mysql:
    image: mysql:8.0
    container_name: investment_portfolio_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: investment_portfolio_manager
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
